### ISSUE TITLE
Fix potentiometer footprint

### ISSUE THREAD

**Issue by cosparks** [supermileage/dynamometer-pcb#17]
The through-holes on the right side of footprint are too far apart vertically.  It seems like they should be within the bounds of, and not centred at the corners of the courtyard.
- holes probably need to be brought in ~1mm towards the center of the courtyard

The potentiometer's mounting supports can be bent so that they fit the current design, so this is not a deal-breaker

**Comment by KevinZhiyuanDing** [comment]
https://github.com/supermileage/dynamometer-pcb/commit/03d35e74a3f1db1f3750efc926a0eced5b3e5ced

**Comment by cosparks** [comment]
@KevinZhiyuanDing I still get notifications for this repo so saw that you are working on this.

I forgot to add that the potentiometer footprint also should be rotated 90° counter-clockwise, so the knob sits in the correct position when it's zeroed.  I'm not sure if knobs for d-shaft pots are standardized, but all the ones that I checked out at lee's electronics were the same.

this is zero (closed)
<img width="200" alt="image" src="https://github.com/supermileage/dynamometer-pcb/assets/20360622/2b5531ab-fb27-4147-9cad-2cf0a252a20a">
but this should be zero:
<img width="200" alt="image" src="https://github.com/supermileage/dynamometer-pcb/assets/20360622/3fe0b852-1418-44dd-93ef-31d18d6b6aaf">

And to fully open the pot you rotate clockwise 270°
