### ISSUE TITLE
Add on/off switch to board

### ISSUE THREAD

**Issue by cosparks** [supermileage/dynamometer-pcb#20]
Among other things, an on/off switch would make it easier to reset the controller.

Add to back or side.  Make sure it aligns with the case.

**Comment by KevinZhiyuanDing** [comment]
@cosparks Hey Colby, would it be okay if we implement the switch externally instead of on the board itself, adding an on off switch between the power source and the power input.

**Comment by cosparks** [comment]
> @cosparks Hey Colby, would it be okay if we implement the switch externally instead of on the board itself, adding an on off switch between the power source and the power input.

that sounds like a very good solution!

**Comment by cosparks** [comment]
Only advantage that I can think of for having it on the board is that it would be more accessible, and could be used with any power supply.

**Comment by KevinZhiyuanDing** [comment]
Ok thanks. Alex, James and I are weighting the options
